apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smap-stt-models-pvc
  namespace: smap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  volumeMode: Filesystem
