apiVersion: v1
kind: Service
metadata:
  name: smap-speech-to-text
  namespace: smap
  labels:
    app: smap-speech-to-text
  annotations:
    metallb.universe.tf/address-pool: smap-pool
    metallb.universe.tf/ip-allocated-from-pool: smap-pool
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30464
  selector:
    app: smap-speech-to-text
